"use client";
import * as React from "react";
import Link from "next/link";
import { Card } from "@/components/ui/card";
import { Badge, Button } from "@/components/ui/primitives";
import { BookOpen, Sparkles, FileText } from "lucide-react";
import { useAnalysis } from "@/hooks/useAnalysis";
import { api } from "@/lib/api";

export default function DocsPage() {
  const { projects, analyses, refreshProjects } = useAnalysis();
  const [items, setItems] = React.useState<any[]>([]);
  const [loading, setLoading] = React.useState(true);

  React.useEffect(() => { refreshProjects(); }, [refreshProjects]);

  React.useEffect(() => {
    let cancelled = false;
    (async () => {
      setLoading(true);
      const list: any[] = [];
      for (const p of projects) {
        for (const a of (analyses[p.id] || [])) {
          if (a.status !== "completed") continue;
          try {
            const findings = await api.listFindings(a.id, { agent: "documentation" });
            for (const f of Array.isArray(findings) ? findings : []) {
              list.push({ project: p, analysis: a, finding: f });
            }
          } catch {}
        }
      }
      if (!cancelled) { setItems(list); setLoading(false); }
    })();
    return () => { cancelled = true; };
  }, [projects, analyses]);

  return (
    <div className="space-y-8">
      <header>
        <h1 className="text-3xl font-bold tracking-tight flex items-center gap-2">
          <BookOpen className="h-7 w-7 text-blue-300" /> Documentation
        </h1>
        <p className="text-white/60 mt-1">
          AI-generated README, API docs, and developer guides for your projects.
        </p>
      </header>

      <div className="space-y-4">
        {loading && <Card className="p-10 text-center text-white/40">Loading documentation…</Card>}
        {!loading && items.length === 0 && (
          <Card className="p-10 text-center text-white/50">
            <Sparkles className="h-10 w-10 mx-auto text-blue-300 mb-2" />
            Documentation is generated by the Documentation Agent. Run an analysis to see it here.
          </Card>
        )}
        {!loading && items.map(({ project, analysis, finding }, idx) => (
          <Card key={`${finding.id}-${idx}`} className="p-5">
            <div className="flex items-center justify-between mb-3 flex-wrap gap-2">
              <div>
                <div className="font-semibold">{project.name}</div>
                <div className="text-xs text-white/40 font-mono">{analysis.id.slice(0, 8)}…</div>
              </div>
              <div className="flex items-center gap-2">
                <Badge color="blue">{finding.category || "documentation"}</Badge>
                <Link href={`/analysis/${analysis.id}`}>
                  <Button variant="ghost" size="sm">View analysis</Button>
                </Link>
              </div>
            </div>
            <h3 className="font-semibold mb-2 flex items-center gap-2">
              <FileText className="h-4 w-4 text-blue-300" /> {finding.title}
            </h3>
            {finding.description && (
              <p className="text-sm text-white/70 mb-3">{finding.description}</p>
            )}
            {finding.extras?.content && (
              <div className="rounded-xl border border-white/10 bg-white/[0.02] p-4">
                <pre className="text-xs font-mono whitespace-pre-wrap text-white/80 max-h-96 overflow-auto leading-relaxed">
                  {finding.extras.content}
                </pre>
              </div>
            )}
            {finding.code_snippet && !finding.extras?.content && (
              <div className="rounded-xl border border-white/10 bg-white/[0.02] p-4">
                <pre className="text-xs font-mono whitespace-pre-wrap text-white/80 max-h-96 overflow-auto leading-relaxed">
                  {finding.code_snippet}
                </pre>
              </div>
            )}
          </Card>
        ))}
      </div>
    </div>
  );
}
