"""
Test Generator Agent — produces pytest unit + integration tests.
"""
from __future__ import annotations

import textwrap
from typing import Any, Dict, List

from .base import AgentResult, BaseAgent


TEMPLATE = textwrap.dedent('''\
    """
    Auto-generated tests for {module}.

    Generated by CodeGuardian AI — review, adjust fixtures and edge cases
    before merging.
    """
    from __future__ import annotations

    import pytest
    {imports}

    {tests}
''')


class TestGeneratorAgent(BaseAgent):
    name = "test"

    async def run(self, payload: Dict[str, Any]) -> AgentResult:
        findings: List[Dict[str, Any]] = []
        for f in payload.get("files", []):
            if f.get("language") not in {"python"}:
                continue
            content = f.get("content", "")
            path = f.get("path", "")
            test_code = await self._generate_for_file(path, content)
            if not test_code:
                continue
            findings.append({
                "category": "tests", "severity": "info",
                "title": f"Generated tests for {path}",
                "description": "Auto-generated pytest module.",
                "file_path": f"tests/test_{path.replace('/', '_').rstrip('.py')}.py",
                "rule_id": "CG-TEST",
                "recommendation": "Save the snippet to the indicated file and run `pytest`.",
                "code_snippet": test_code,
            })
        return AgentResult(
            agent_name=self.name,
            findings=findings[:30],
            output={"generated": len(findings)},
            summary={"score": min(100.0, 50.0 + len(findings) * 5.0), "total": len(findings)},
            confidence=0.7,
        )

    async def _generate_for_file(self, path: str, content: str) -> str:
        if not content.strip():
            return ""
        sample = content[:3500]
        prompt = (
            "Generate a pytest test module for the following source. Cover normal cases, edge "
            "cases, and at least one failure case. Use `unittest.mock` if helpful. "
            "Return JSON with `imports` (a python list of strings) and `tests` (a list of full "
            "test function definitions as strings).\n\n"
            f"File: {path}\n```python\n{sample}\n```"
        )
        try:
            data = await self._llm_json(prompt, fast=True)
        except Exception:
            return ""
        imports = "\n    ".join(data.get("imports") or [""])
        tests = "\n\n    ".join(data.get("tests") or [""])
        if not tests:
            return ""
        return TEMPLATE.format(module=path, imports=imports, tests=tests)
